name = "PhoXonic"
uuid = "f8e5d5a0-1234-4567-89ab-cdef01234567"
authors = ["Hiroharu Sugawara <hsugawa@gmail.com>"]
version = "0.1.1"

[deps]
Brillouin = "23470ee3-d0df-4052-8b1a-8cbd6363e7f0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
IterativeSolvers = "42fd0dbc-a981-5370-80f2-aaf504508153"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
Krylov = "ba0b0d4f-ebba-5204-a429-3ac8c609bfb7"
KrylovKit = "0b1a1467-8014-51b9-945f-bf0ae24f4b77"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LinearMaps = "7a12625a-238d-50fd-b39a-03d52299707e"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[weakdeps]
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
ReducedShiftedKrylov = "4d429029-a74f-409e-95c5-00936df3696f"

[extensions]
PhoXonicPlotsExt = "Plots"
PhoXonicReducedShiftedKrylovExt = "ReducedShiftedKrylov"

[compat]
Brillouin = "0.5"
FFTW = "1"
IterativeSolvers = "0.9.4"
JLD2 = "0.4, 0.5"
Krylov = "0.10"
KrylovKit = "0.10.2"
LinearMaps = "3"
Plots = "1"
ReducedShiftedKrylov = "0.1"
StaticArrays = "1"
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
